package org.novastack.iposca.rpt.service;

import org.novastack.iposca.config.AppConfig;
import org.novastack.iposca.config.AppConfigAPI;
import org.novastack.iposca.rpt.model.DebtChangeData;
import org.novastack.iposca.rpt.model.StockItem;
import org.novastack.iposca.rpt.model.TurnoverData;
import org.novastack.iposca.stock.Stock;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class ReportService {

    private final String currentUser;

    public ReportService(String currentUser) {
        this.currentUser = currentUser;
    }

    public TurnoverData getTurnoverData(LocalDate startDate, LocalDate endDate) throws SQLException{
        TurnoverData data = new TurnoverData();
        data.setReportPeriodStart(startDate);
        data.setReportPeriodEnd(endDate);
        data.setGeneratedBy(currentUser);
        data.setGeneratedTimestamp(LocalDate.now());

        data.setTotalSalesCount(0);
        data.setTotalSalesAmount(0f);
        data.setTotalOrdersPlacedValue(0f);

        logReport("TURNOVER_REPORT", "Period: " + startDate + " to " + endDate);
        return data;
    }

    public List<StockItem> getStockData(String stockStatus, String searchText) throws SQLException {
        String status = stockStatus == null ? "ALL" : stockStatus.trim().toUpperCase(Locale.ROOT);
        String search = searchText == null ? "" : searchText.trim().toLowerCase(Locale.ROOT);
        float vatRate = getVatRate();

        List<StockItem> reportRows = new ArrayList<>();
        for (Stock stock : Stock.getAllStock()) {
            if (!matchesStockStatus(stock, status) || !matchesSearch(stock, search)) {
                continue;
            }

            float retailPrice = calculateRetailPrice(stock.getBulkCost(), stock.getMarkupRate());
            float totalStockValue = retailPrice * stock.getQuantity();
            float vatAmount = totalStockValue * (vatRate / 100f);

            StockItem item = new StockItem(
                    stock.getId(),
                    stock.getName(),
                    stock.getBulkCost(),
                    stock.getQuantity(),
                    stock.getStockLimit()
            );
            item.setLowStock(stock.getQuantity() <= stock.getStockLimit());
            item.setRetailPrice(retailPrice);
            item.setVatRate(vatRate);
            item.setVatAmount(vatAmount);
            item.setTotalStockValue(totalStockValue);

            reportRows.add(item);
        }

        logReport("STOCK_REPORT", "Status: " + status + ", Search: " + search);
        return reportRows;
    }

    public DebtChangeData getDebtChangeData(LocalDate startDate, LocalDate endDate) throws SQLException {
        DebtChangeData data = new DebtChangeData();
        data.setStartDate(startDate);
        data.setEndDate(endDate);
        data.setGeneratedBy(currentUser);
        data.setGeneratedTimestamp(LocalDate.now());

        data.setOpeningAggregateDebt(0f);
        data.setPaymentsReceived(0f);
        data.setNewDebtAccrued(0f);
        data.setClosingAggregateDebt(0f);
        data.setTotalDebtorsCount(0);
        data.setTotalPaymentsCount(0);
        data.setTotalCreditSalesCount(0);

        logReport("DEBT_REPORT", "Period: " + startDate + " to " + endDate);
        return data;
    }

    private void logReport(String reportType, String details) {
        System.out.println("AUDIT: " + reportType + " generated by " + currentUser + " - " + details);
    }

    private boolean matchesStockStatus(Stock stock, String status) {
        return switch (status) {
            case "LOW_STOCK" -> stock.getQuantity() > 0 && stock.getQuantity() <= stock.getStockLimit();
            case "OUT_OF_STOCK" -> stock.getQuantity() <= 0;
            default -> true;
        };
    }

    private boolean matchesSearch(Stock stock, String search) {
        if (search.isEmpty()) {
            return true;
        }

        return String.valueOf(stock.getId()).contains(search)
                || stock.getName().toLowerCase(Locale.ROOT).contains(search);
    }

    private float calculateRetailPrice(float bulkCost, int markupRate) {
        return bulkCost * (1 + (markupRate / 100f));
    }

    private float getVatRate() {
        try {
            byte[] vat = AppConfig.get(AppConfig.ConfigKey.VAT);
            return vat == null ? 0f : AppConfigAPI.decodeByteToInt(vat);
        } catch (IllegalArgumentException e) {
            return 0f;
        }
    }
}



