package org.novastack.iposca.rpt.service;

import org.novastack.iposca.rpt.model.DebtChangeData;
import org.novastack.iposca.rpt.model.StockItem;
import org.novastack.iposca.rpt.model.TurnoverData;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class ReportService {

    private final String currentUser;

    public ReportService(String currentUser) {
        this.currentUser = currentUser;
    }

    public TurnoverData getTurnoverData(LocalDate startDate, LocalDate endDate) throws SQLException{
        TurnoverData data = new TurnoverData();
        data.setReportPeriodStart(startDate);
        data.setReportPeriodEnd(endDate);
        data.setGeneratedBy(currentUser);
        data.setGeneratedTimestamp(LocalDate.now());

        data.setTotalSalesCount(0);
        data.setTotalSalesAmount(0f);
        data.setTotalOrdersPlacedValue(0f);

        logReport("TURNOVER_REPORT", "Period: " + startDate + " to " + endDate);
        return data;
    }

    public List<StockItem> getStockData(String stockStatus, String searchText) throws SQLException {
        return new ArrayList<>();
    }

    public DebtChangeData getDebtChangeData(LocalDate startDate, LocalDate endDate) throws SQLException {
        DebtChangeData data = new DebtChangeData();
        data.setStartDate(startDate);
        data.setEndDate(endDate);
        data.setGeneratedBy(currentUser);
        data.setGeneratedTimestamp(LocalDate.now());

        data.setOpeningAggregateDebt(0f);
        data.setPaymentsReceived(0f);
        data.setNewDebtAccrued(0f);
        data.setClosingAggregateDebt(0f);
        data.setTotalDebtorsCount(0);
        data.setTotalPaymentsCount(0);
        data.setTotalCreditSalesCount(0);

        logReport("DEBT_REPORT", "Period: " + startDate + " to " + endDate);
        return data;
    }

    private void logReport(String reportType, String details) {
        System.out.println("AUDIT: " + reportType + " generated by " + currentUser + " - " + details);
    }
}




